### ISSUE TITLE
Infinite scroll fetches everything

### ISSUE THREAD

**Issue by pilsnerfrajz** [Cactooz/StarWarsWiki#58]
## Bug
Infinite scroll fetches everything because scroll gets stuck. 

## To reproduce
Scroll down to the "bottom" of a browse view and quickly click on a card before the next page is fetched. Then use the arrow button to go back to browse. If you don't scroll after going back, infinite scroll will fetch all the data available and keep scrolling. Normally you have to scroll down manually to fetch the next page. 

Seems to be exclusively on Mac. Hitting the border with scroll causes a bounce that may be the cause.

**Comment by pilsnerfrajz** [comment]
This bug seems to have been fixed when changing the fetch function and with the styling of the pages. If everyone agree, we should close the issue as fixed.

**Comment by Cactooz** [comment]
It should be closed as not planned instead of not fixed but otherwise yes :)
